# Generated by Django 5.1.2 on 2024-10-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='carbon_emission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_emission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
