# Generated by Django 5.1.2 on 2024-10-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_category_recipe_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe_ingredients', to='recipes.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=models.ManyToManyField(related_name='recipe_category', to='recipes.category'),
        ),
    ]
