# Generated by Django 5.1.2 on 2024-11-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_add_recipe_ingredients_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
